import {FormEvent,useEffect,useState} from 'react';
import {api,messageOf} from '../services/api';
import {Empty,Modal,PageTitle} from '../components/UI';
import {useAuth} from '../context/AuthContext';

export default function Reports(){
  const {user}=useAuth();const isSuper=user?.role==='SUPER_ADMIN';
  const [rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[editing,setEditing]=useState<any|null>(null),[err,setErr]=useState(''),[pageErr,setPageErr]=useState('');
  async function load(){try{setPageErr('');const r=await api.get('/reports');setRows(r.data)}catch(e){setPageErr(messageOf(e))}}
  useEffect(()=>{void load()},[]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setErr('');try{const body=Object.fromEntries(new FormData(e.currentTarget).entries());if(editing)await api.put(`/reports/${editing.id}`,body);else await api.post('/reports',body);setShow(false);setEditing(null);await load()}catch(e){setErr(messageOf(e))}}
  async function review(id:number,decision:'APPROVE'|'NEEDS_CHANGES'|'REJECT'){try{let reviewComment='';if(decision!=='APPROVE'){reviewComment=prompt(decision==='REJECT'?'Reason for rejection:':'What changes are required?')||'';if(!reviewComment.trim())return;}await api.put(`/reports/${id}/review`,{decision,reviewComment});await load()}catch(e){alert(messageOf(e))}}
  async function remove(id:number){if(!confirm('Delete this daily report?'))return;try{await api.delete(`/reports/${id}`);await load()}catch(e){alert(messageOf(e))}}
  function canReview(r:any){if(!user||r.employee_id===user.employeeId)return false;if(user.role==='SUPER_ADMIN')return ['PENDING','APPROVED_BY_TEAM_LEAD','APPROVED_BY_ADMIN'].includes(r.review_status);if(user.role==='ADMIN')return ['PENDING','APPROVED_BY_TEAM_LEAD'].includes(r.review_status);if(user.role==='TEAM_LEAD')return r.review_status==='PENDING';return false}
  function statusText(status:string){return ({PENDING:'Awaiting Team Lead / higher review',APPROVED_BY_TEAM_LEAD:'Team Lead approved • Awaiting Admin / Super Admin',APPROVED_BY_ADMIN:'Admin approved • Awaiting Super Admin',REVIEWED:'Fully approved',NEEDS_CHANGES:'Needs changes',REJECTED:'Rejected'} as any)[status]||status}
  return <><PageTitle title="Daily Work Reports" subtitle="Daily accomplishments with Team Lead → Admin → Super Admin approval hierarchy" action={<button className="btn btn-accent" onClick={()=>{setEditing(null);setShow(true)}}>+ Submit Report</button>}/>
  {pageErr&&<div className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{pageErr}</div>}
  {rows.length?<div className="space-y-4">{rows.map(r=><div className="card p-5" key={r.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-extrabold">{user?.role==='EMPLOYEE'?'My Report':r.employee_name}</h3>{user?.role!=='EMPLOYEE'&&<div className="text-xs font-semibold text-orange">{r.employee_code} • {r.user_type} • {r.department_name||'No department'}</div>}<div className="text-sm muted">{new Date(r.report_date).toLocaleDateString()}</div></div><div className="flex items-center gap-2"><span className="badge">{statusText(r.review_status)}</span>{isSuper&&<><button className="btn !px-3 !py-1.5" onClick={()=>{setEditing(r);setShow(true)}}>Edit</button><button className="btn !px-3 !py-1.5 text-red-600" onClick={()=>remove(r.id)}>Delete</button></>}</div></div>
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><div><div className="label">Completed</div><p className="mt-1 text-sm">{r.completed_work}</p></div><div><div className="label">Tomorrow</div><p className="mt-1 text-sm">{r.tomorrow_plan||'—'}</p></div><div><div className="label">Blockers</div><p className="mt-1 text-sm">{r.blockers||'None'}</p></div><div><div className="label">Hours Worked</div><p className="mt-1 text-sm">{r.hours_worked||'—'}</p></div></div>
  <div className="mt-4 rounded-lg bg-slate-50 p-3 text-xs"><b>Approval flow:</b> Team Lead → Admin → Super Admin. A higher-level reviewer may approve directly and skip pending lower levels.</div>
  {r.review_comment&&<div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm"><b>Latest review comment:</b> {r.review_comment}</div>}
  {canReview(r)&&<div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-accent" onClick={()=>review(r.id,'APPROVE')}>Approve</button><button className="btn" onClick={()=>review(r.id,'NEEDS_CHANGES')}>Needs Changes</button><button className="btn text-red-600" onClick={()=>review(r.id,'REJECT')}>Reject</button></div>}</div>)}</div>:!pageErr&&<Empty/>}
  {show&&<Modal title={editing?'Edit Daily Work Report':'Submit Daily Work Report'} onClose={()=>{setShow(false);setEditing(null)}}><form onSubmit={save} className="space-y-4"><input className="input" type="date" name="reportDate" defaultValue={editing?.report_date?.slice?.(0,10)||''}/><textarea className="input min-h-24" name="completed" placeholder="What did you complete today?" defaultValue={editing?.completed_work||''} required/><textarea className="input" name="tasksWorked" placeholder="Tasks worked on" defaultValue={editing?.tasks_worked||''}/><input className="input" name="hoursWorked" type="number" step="0.25" min="0" max="24" placeholder="Hours worked" defaultValue={editing?.hours_worked??''}/><textarea className="input" name="blockers" placeholder="Problems / blockers" defaultValue={editing?.blockers||''}/><textarea className="input" name="tomorrowPlan" placeholder="Plan for tomorrow" defaultValue={editing?.tomorrow_plan||''}/><textarea className="input" name="comments" placeholder="Additional comments" defaultValue={editing?.comments||''}/>{err&&<div className="text-red-600">{err}</div>}<button className="btn btn-primary">{editing?'Save Changes':'Submit Report'}</button></form></Modal>}</>;
}
